In [1]:
#importing requires libraries
import pandas as pd
import numpy as np 
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('/home/yashika/finaldata.csv')
df

,State/UT,Year,population(total),Rural,Urban,Tot_M,Tot_F,P_LIT,M_LIT,F_LIT,...,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES,Total Crimes,tot_crimes_sc,total crime against women,Total crimes against STs,Total crime against children,Crime Rate
0,A& N ISLANDS,2001,356152,239954,116198,192972,163180,253135.0,146831.0,106304,...,0,0,323,658,1386,0,34.0,1.0,0.0,184.752578
1,ANDHRA PRADESH,2001,76210007,55401067,20808940,38527413,37682594,39934323.0,23444788.0,16489535,...,7,7400,34344,130089,278982,2933,13669.0,512.0,270.0,170.698055
2,ARUNACHAL PRADESH,2001,1097968,870087,227881,579941,518027,484785.0,303281.0,181504,...,0,0,618,2342,5243,0,180.0,72.0,0.0,213.303120
3,ASSAM,2001,26655528,23216288,3439240,13777037,12878491,14015354.0,8188697.0,5826657,...,0,2010,9315,36877,81418,6,4048.0,0.0,18.0,138.346537
4,BIHAR,2001,82998509,74316709,8681800,43243795,39754714,31109577.0,20644376.0,10465201,...,83,2406,36667,88432,189612,1303,4489.0,83.0,83.0,106.546492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,TAMIL NADU,2012,72867204,40524361,32342843,36680044,36477172,53274562.0,28573260.0,24701302,...,0,15499,124176,200474,415626,1647,6381.0,27.0,1036.0,275.122399
416,TRIPURA,2012,3717661,3088869,628792,1889371,1826534,2897340.0,1538903.0,1355550,...,0,10,1742,6264,13461,76,1559.0,29.0,20.0,168.493039
417,UTTAR PRADESH,2012,202226609,159783555,42443054,107092522,96666476,118889202.0,70418482.0,48470720,...,0,14406,68538,198093,444403,6202,23033.0,44.0,6033.0,97.955952
418,UTTARAKHAND,2012,10260421,7670906,2589515,5240528,5136562,7100774.0,3971891.0,3128883,...,0,670,2118,8882,20122,33,1055.0,3.0,122.0,86.565649
419,WEST BENGAL,2012,92575564,66749935,25825629,47417544,45045160,63274096.0,34529005.0,28745091,...,12,4385,64482,161427,353008,85,30585.0,91.0,1706.0,174.373229

Data have been collected from the different websites manually for the population,area of each state and literacy rate of each state .The data was available for the year #2001 and #2012 for population, area and literacy rate of each state. So, necassary calculations and assumptions were made in order to achive the data for the year #2002 to #2010 & year #2012..Several websites were used in order to fetch the data for the same. Some of them are:-

https://en.wikipedia.org/wiki/List_of_states_in_India_by_past_population
https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area
https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_literacy_rate
https://socialjustice.gov.in/common/76669
http://cyberjournalist.org.in/census/cenindia.html
https://www.indiastat.com/specimen-tables/geographical-data
https://www.wbhealth.gov.in/other_files/2007/14_5.html
https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_population
https://www.prb.org/wp-content/uploads/2011/04/india-population-2001-2011.pdf
https://censusindia.gov.in/nada/index.php/catalog/20030
https://scikit-learn.org/stable/user_guide.html 
https://github.com/ 
https://www.kaggle.com/ 
https://medium.com/ 
https://towardsdatascience.com/ 
https://www.analyticsvidhya.com/ 
https://www.geeksforgeeks.org/
https://www.latestlaws.com/wp-content/uploads/2018/07/National-Crime-Record-Bureau-Report-NCRB-2012.pdf